import type { Box } from '../../types/geometry';
import type { Material, MaterialId } from '../../types/materials';
import type { InteriorItem, ShelfItem } from '../../types/interior';
import type { CutItem, CutGroup } from '../../types/cuts';
import type { Edging } from '../../types/edging';
import type { BoxSlotId } from '../../types/project';
import { newItemId, boxStableKey } from '../interior/interiorUtils';

// ── BoardModel ────────────────────────────────────────────────────────────────
// Per-body physical model: every carcass panel (sides, top, bottom, shelves,
// partition, envelope, plinth, back) becomes a `Board` with explicit
// dimensions and a visual rectangle in front-view coordinates. Drives both
// the "cut" sketch and the cut list (via `boardsToCutItems`).
//
// Coordinate convention (per box, front view):
//   x = 0  → outer-left edge of the body
//   x = W  → outer-right edge of the body
//   y = 0  → outer-top edge of the body
//   y = H  → outer-bottom edge of the body
// Envelope boards live at x < 0 / x > W and y < 0. Plinth boards live at
// y > H (below the body).

export type BoardRole =
  | 'side-left'
  | 'side-right'
  | 'top'
  | 'bottom'
  | 'shelf'
  | 'partition'
  | 'fixed-shelf'
  | 'internal-shelf'
  | 'envelope-left'
  | 'envelope-right'
  | 'envelope-top'
  | 'back'
  | 'plinth-front'
  | 'plinth-back'
  | 'plinth-gable-a'
  | 'plinth-gable-b'
  | 'plinth-front-cladding'
  /** Sink-unit traverses: replace the top board with two narrow cross-braces
   *  so the sink basin can drop in from above. */
  | 'sink-traverse-front'
  | 'sink-traverse-back';

export interface Board {
  /** Ad-hoc identifier — freshly generated by every `buildBoardModel` call.
   *  Use as the React key for rendering, NOT as a persistence key. */
  id: string;
  /** Stable identifier that survives `calculate()` rebuilds — every call
   *  to the build function with the same logical board produces the same
   *  `stableId`. Used as the key in board-override maps so an override
   *  attached by the user persists across recalculations even though the
   *  ad-hoc `id` changes. Built by {@link boardStableId} with the role and
   *  an optional container sub-key (e.g. `boxStableKey(box)`, a gable id,
   *  or a shelf item id). Examples:
   *    'side-left@bottom:left'
   *    'shelf@bottom:left@s_abc123'
   *    'internal-shelf@bottom:left@h120'
   *    'plinth-front'                    (cabinet-level singleton)
   *    'plinth-gable-a@joint:0' */
  stableId: string;
  role: BoardRole;
  materialId: MaterialId | string;  // MaterialId for catalog, string for custom materials
  /** cm — physical length of the cut piece (the long dimension). */
  length: number;
  /** cm — physical width of the cut piece (typically equals box.D). */
  width: number;
  /** cm — material thickness. */
  thickness: number;
  /** cm — visual front-view rect, left edge. */
  xFrom: number;
  /** cm — visual front-view rect, right edge. */
  xTo: number;
  /** cm — visual rect, top edge (y grows downward). For carcass / envelope
   *  / back / shelf roles this is the FRONT-VIEW Y (vertical, body-local).
   *  For plinth-* roles, y means DEPTH (top-view): yFrom is closer to the
   *  cabinet front, yTo is closer to the back. The dual semantic keeps
   *  every board in one rectangular footprint; renderers read the field
   *  according to the board's role family. */
  yFrom: number;
  /** cm — visual rect, bottom edge. See `yFrom` for the dual semantic. */
  yTo: number;
  /** Whether this board is rendered by the cross-section sketch. The back
   *  panel sits BEHIND the carcass so it is invisible in front view, but it
   *  is still emitted into the cut list. */
  visible: boolean;
}

// ── Stable id + per-board override layer ───────────────────────────────────
// Every board carries a `stableId` (built by {@link boardStableId}) that
// survives `calculate()` rebuilds. `useCabinet` keeps a `Map<stableId,
// BoardOverrides>` separately from the board list — overrides live OUTSIDE
// the Board so resets revert to the derived value without rebuilding the
// model. Consumers read effective values via {@link getDimension} /
// {@link getMaterial}; the carpentry-rule formulas remain the single source
// of derivation inside `buildBoardModel` / `buildPlinthBoardModel`.

/** Concatenates a role with an optional container sub-key into a canonical
 *  stable id. Returns `{role}@{subKey}` when `subKey` is set, otherwise the
 *  role alone (for cabinet-level singletons). The `@` separator is reserved
 *  — callers must not embed it in their sub-keys. */
export function boardStableId(role: BoardRole, subKey?: string): string {
  return subKey !== undefined && subKey !== '' ? `${role}@${subKey}` : role;
}

/** Which board dimension is being overridden. `materialId` is its own
 *  channel (see {@link BoardOverrides.materialId}) — kept off this union so
 *  the dimension-only setters/getters stay numeric. */
export type BoardDimensionKey = 'length' | 'width' | 'thickness';

/** Sparse per-board override. A partial `dimensions` only carries the keys
 *  the user changed; unchanged keys fall through to the derived value. The
 *  same for `materialId`. `edging` is the highest-precedence layer of the
 *  edging override chain (see {@link resolveEdging}) — also sparse, present
 *  only when the user has chosen a per-board band. */
export interface BoardOverrides {
  dimensions?: Partial<Record<BoardDimensionKey, number>>;
  materialId?: MaterialId;
  edging?: Edging;
}

/** Effective dimension value = override ?? derived. Same pattern as
 *  `userPositionX ?? defaultPlinthGableLeftX(...)` for plinth gables. */
export function getDimension(
  board: Board,
  key: BoardDimensionKey,
  overrides: ReadonlyMap<string, BoardOverrides>,
): number {
  return overrides.get(board.stableId)?.dimensions?.[key] ?? board[key];
}

/** Effective material id = override ?? derived. The override drives the cut
 *  list's grouping when the carpenter wants a single board cut from a
 *  different sheet (e.g. real-wood back panel in an otherwise MDF cabinet). */
export function getMaterial(
  board: Board,
  overrides: ReadonlyMap<string, BoardOverrides>,
): MaterialId | string {
  return overrides.get(board.stableId)?.materialId ?? board.materialId;
}

// ── Edging — visibility patterns, deductions, override chain ───────────────
// Edge banding is a thin strip applied to a panel's visible cut edge(s).
// The carpentry rule has two facets:
//
//   1. WHICH edges get a band — determined by the board's role, not the
//      user's choice. Body panels with a visible front cut get the band on
//      that single edge (`'front'`). Doors and external-drawer fronts are
//      facade pieces with all four edges exposed — perimeter band
//      (`'perimeter'`). Hidden surfaces (back panel, every plinth-* role)
//      get nothing (`'none'`).
//
//   2. WHAT band — three override layers, resolved most-specific first:
//        per-board (`BoardOverrides.edging`)
//        per-body  (`bodyEdgingOverrides[boxSlotId]`)
//        cabinet-wide default (`CabinetInput.edging ?? DEFAULT_EDGING`).
//      A finishMaterialId of `undefined` after resolution means "auto" —
//      the band's color matches the board's effective material, computed
//      by `getEdgingFinishMaterial`.

export type EdgingPattern = 'none' | 'front' | 'perimeter';

/** Maps a `BoardRole` to its edging pattern. `'perimeter'` is reserved for
 *  doors / external-drawer fronts (emitted by `cuttingList`, not by
 *  `buildBoardModel`) — no board role here returns it. The plinth family is
 *  excluded from edging on purpose: the cladding/front strips sit under the
 *  door line and aren't worth banding in our defaults. */
export function getEdgingPattern(role: BoardRole): Exclude<EdgingPattern, 'perimeter'> {
  switch (role) {
    case 'back':
    case 'plinth-front':
    case 'plinth-back':
    case 'plinth-gable-a':
    case 'plinth-gable-b':
    case 'plinth-front-cladding':
      return 'none';
    case 'side-left':
    case 'side-right':
    case 'top':
    case 'bottom':
    case 'shelf':
    case 'fixed-shelf':
    case 'internal-shelf':
    case 'partition':
    case 'envelope-left':
    case 'envelope-right':
    case 'envelope-top':
    case 'sink-traverse-front':
    case 'sink-traverse-back':
      return 'front';
  }
}

/** Edge-band deduction in cm on a single dimension.
 *  - `'none'`: always 0.
 *  - `'front'`: 1× thickness/10 on `width` (the depth axis of body panels),
 *    0 on `length`. `'thickness'` is never deducted — the band wraps the
 *    face, not the panel's thickness.
 *  - `'perimeter'`: 2× thickness/10 on BOTH `length` and `width` (band on
 *    every side of the same axis).
 *
 *  Convention: a body board's visible front edge runs along its depth
 *  (stored as `width`). So `length` deductions only appear for perimeter
 *  pieces, which is why door/drawer-front cuts have to opt into
 *  `'perimeter'` explicitly when they call this. */
export function getDeductionFor(
  pattern: EdgingPattern,
  dimensionKey: BoardDimensionKey,
  edging: Edging,
): number {
  if (pattern === 'none' || dimensionKey === 'thickness') return 0;
  const tCm = edging.thickness / 10;
  if (pattern === 'perimeter') return 2 * tCm;
  return dimensionKey === 'width' ? tCm : 0;
}

/** Override-chain context for {@link resolveEdging}. The maps are the live
 *  state held by `useCabinet`; the cabinet default is typically
 *  `input.edging ?? DEFAULT_EDGING`. */
export interface EdgingContext {
  cabinetDefault: Edging;
  bodyOverrides: ReadonlyMap<BoxSlotId, Edging>;
  /** Same map used for dimension/material overrides — the `edging` field
   *  is the per-board edging override. */
  boardOverrides: ReadonlyMap<string, BoardOverrides>;
}

/** Walks the override chain (per-board → per-body → cabinet default) and
 *  returns the effective edging for `board`. `boxSlotId` is the slot the
 *  board belongs to; pass `undefined` for cabinet-level singletons (the
 *  plinth family) so the body layer is skipped — those boards normally
 *  resolve to pattern `'none'` anyway, but the resolver stays well-defined. */
export function resolveEdging(
  board: Board,
  boxSlotId: BoxSlotId | undefined,
  ctx: EdgingContext,
): Edging {
  const boardOv = ctx.boardOverrides.get(board.stableId)?.edging;
  if (boardOv !== undefined) return boardOv;
  if (boxSlotId !== undefined) {
    const bodyOv = ctx.bodyOverrides.get(boxSlotId);
    if (bodyOv !== undefined) return bodyOv;
  }
  return ctx.cabinetDefault;
}

/** Resolves the band's actual finish material. When the edging carries an
 *  explicit `finishMaterialId`, returns it as-is. When `undefined` ("auto"),
 *  returns the board's effective material via {@link getMaterial} — so the
 *  band's color follows whichever sheet the panel ends up cut from,
 *  including a per-board material override. */
export function getEdgingFinishMaterial(
  board: Board,
  edging: Edging,
  boardOverrides: ReadonlyMap<string, BoardOverrides>,
): MaterialId | string {
  return edging.finishMaterialId ?? getMaterial(board, boardOverrides);
}

// ── Constants ────────────────────────────────────────────────────────────────

/** Per-side reveal on shelf width. Kept at 0 so a shelf is cut to exactly
 *  the same length as the top/bottom panel (`W − 2·tBody`). The constant is
 *  retained as a structural seam — re-enable here if a future carpentry
 *  convention calls for a clearance reveal. cm. */
export const SHELF_WIDTH_REVEAL_CM = 0;

/** Total depth reduction on shelves. Kept at 0 so a shelf width matches
 *  the body depth `D` exactly (same as top/bottom). cm. */
export const SHELF_DEPTH_REVEAL_CM = 0;

/** Back-panel thickness — default 5 mm sheet. Overridable per-call via
 *  `backThicknessCm` in BuildBoardModelArgs (and per-cabinet via the form
 *  field "עובי גב"). cm. */
export const BACK_THICKNESS_CM = 0.5;

/** Hinge gap between the carcass front edge and the front panel — fixed
 *  by the hinge cup geometry. cm. Drives the carcass-depth reduction:
 *  `carcassD = cabinetD - backThickness - HINGE_GAP_CM - frontThickness`. */
export const HINGE_GAP_CM = 0.3;

/** Floor clearance under the outer envelope side panels — the cabinet rests
 *  on plastic levelers ~6 mm tall, so the envelope sides are cut short by
 *  this amount to leave room. cm. Affects only `envelope-left` /
 *  `envelope-right` cut length. */
export const LEVELER_GAP_CM = 0.6;

// ── Cabinet-derived dimension helpers ───────────────────────────────────────
// Single-source-of-truth formulas for values used by both `useCabinet` (the
// production calc) and the live sketches (which run BEFORE calculate from raw
// form inputs). Centralising them here keeps the UI from re-deriving the
// same arithmetic in three different places.

/** Carcass depth = cabinet D minus the front-side reductions every body
 *  panel shares (back-panel thickness, hinge-cup gap, front material).
 *  Returns ≥ 0. */
export function computeCarcassDepth(
  D: number,
  backThicknessCm: number,
  hingeGapCm: number,
  tFrontCm: number,
): number {
  return Math.max(0, D - backThicknessCm - hingeGapCm - tFrontCm);
}

/** Inner cabinet width = W minus the shell's front panels (per side).
 *  Accepts either a boolean (symmetric — both sides have shell or neither)
 *  or an explicit `{ left, right }` object for kitchen units where the
 *  carpenter may disable one side (cabinet flush against a wall). */
export function computeInnerWidth(
  W: number,
  shell: boolean | { left: boolean; right: boolean },
  tFrontCm: number,
): number {
  if (typeof shell === 'boolean') return shell ? W - 2 * tFrontCm : W;
  return W - (shell.left ? tFrontCm : 0) - (shell.right ? tFrontCm : 0);
}

// ── Joint method ─────────────────────────────────────────────────────────────
// Rabbet: sides span full height; top/bottom slot between the sides.
//   → narrow / tall cabinets (W ≤ 2·H), where the sides carry the load.
// Butt:  top/bottom span full width; sides slot between top and bottom.
//   → wide / short cabinets (W > 2·H), where the top/bottom carry the load.

export type JointMethod = 'rabbet' | 'butt';

/** Per-body helper kept for legacy callers / unit tests. Production code
 *  (`useCabinet`, `CabinetSketch`) decides the joint method ONCE per cabinet
 *  via {@link resolveCabinetJointMethod} so all bodies in a multi-row
 *  cabinet share the same top/bottom-panel cut formula. */
export function resolveJointMethod(box: Box): JointMethod {
  return box.W > 2 * box.H ? 'butt' : 'rabbet';
}

/** Cabinet-level joint method. Takes the user's H and W input (the external
 *  cabinet dimensions including plinth) so multi-row cabinets do not flip
 *  joint between rows when one row's box.H drops below the W/2 threshold.
 *  Carpentry intent: a tall cabinet rests load on its sides (rabbet);
 *  a wide-short cabinet rests load on its top/bottom (butt). The overall
 *  cabinet's slenderness drives the choice — not the slenderness of any
 *  individual row. */
export function resolveCabinetJointMethod(cabinetW: number, cabinetH: number): JointMethod {
  return cabinetW > 2 * cabinetH ? 'butt' : 'rabbet';
}

// ── Envelope flag derivation ─────────────────────────────────────────────────
// Centralised so CabinetSketch (renderer) and useCabinet (cuts) agree on
// which boxes carry the cabinet's outer envelope. Without a shell, no
// envelope. With a shell:
//  - envelope-left   on the leftmost body of any row (position 'left',
//                    'single', or unit_1).
//  - envelope-right  on the rightmost (position 'right', 'single', or the
//                    last unit in its row).
//  - envelope-top    on the top row only (level 'top' or 'single'), when
//                    the user also enabled `hasEnvelopeTop`.

export function deriveEnvelopeFlags(
  box: Box,
  shell: boolean | { left: boolean; right: boolean },
  hasEnvelopeTop: boolean,
): { hasEnvelopeLeft: boolean; hasEnvelopeRight: boolean; hasEnvelopeTop: boolean } {
  const sides = typeof shell === 'boolean' ? { left: shell, right: shell } : shell;
  if (!sides.left && !sides.right) {
    return { hasEnvelopeLeft: false, hasEnvelopeRight: false, hasEnvelopeTop: false };
  }
  const isUnit = box.position.startsWith('unit_');
  const isLeftEdge =
    box.position === 'left' ||
    box.position === 'single' ||
    (isUnit && box.unitIndex === 1);
  const isRightEdge =
    box.position === 'right' ||
    box.position === 'single' ||
    (isUnit && box.unitIndex !== undefined && box.unitIndex === box.unitTotal);
  // Envelope side panels span the FULL cabinet height — they are a single
  // physical board, not split per level. Only the bottom-most row (or the
  // only row) emits them so the cut list doesn't get duplicate entries.
  const isBottomRow = box.level === 'bottom' || box.level === 'single';
  const isTopRow = box.level === 'top' || box.level === 'single';
  return {
    hasEnvelopeLeft: sides.left && isLeftEdge && isBottomRow,
    hasEnvelopeRight: sides.right && isRightEdge && isBottomRow,
    hasEnvelopeTop: hasEnvelopeTop && isTopRow,
  };
}

// ── Build ────────────────────────────────────────────────────────────────────

export interface BuildBoardModelArgs {
  box: Box;
  bodyMaterial: Material | (Omit<Material, 'id'> & { id: string });
  frontMaterial: Material | (Omit<Material, 'id'> & { id: string });
  /** Outer envelope on the left edge — true only when this box sits at the
   *  cabinet's left edge AND a shell is present. */
  hasEnvelopeLeft: boolean;
  /** Outer envelope on the right edge. */
  hasEnvelopeRight: boolean;
  /** Outer envelope on top — true for the topmost row only. */
  hasEnvelopeTop: boolean;
  /** Items in this body (or in this cell for a partitioned body). Used to
   *  emit shelf and fixed-shelf boards. Drawers, rods, and internal drawers
   *  are not boards — they are ignored here. */
  items: InteriorItem[];
  /** Whether this body has a vertical partition. */
  hasPartition: boolean;
  /** For partitioned bodies: items of cell 0 (right) and cell 1 (left).
   *  When present, `items` is ignored for shelves; each cell's shelves are
   *  emitted with cell-width xFrom/xTo. */
  cellItems?: [InteriorItem[], InteriorItem[]];
  /** Include a back panel (visible:false). Defaults to true. */
  hasBack?: boolean;
  /** Outer envelope depth in cm — used for envelope-* board `width`. The
   *  envelope spans the full cabinet depth, while box.D is the (smaller)
   *  carcass depth (= cabinetD − backThickness − HINGE_GAP − frontThickness).
   *  Defaults to box.D when not provided (legacy callers / unit tests). */
  envelopeDepth?: number;
  /** Back-panel thickness in cm. Defaults to `BACK_THICKNESS_CM`. The form
   *  exposes this as the "עובי גב" field; callers pass the user value
   *  here so the back-panel cut emits the right thickness. */
  backThicknessCm?: number;
  /** Full cabinet height in cm (top of envelope-top to floor — i.e. the
   *  user's H input, which already includes plinth). Drives the cut length
   *  of envelope-left / envelope-right: those side panels span the WHOLE
   *  cabinet side and are shortened by `LEVELER_GAP_CM` so they sit on
   *  plastic levelers. Defaults to box.H for legacy / unit-test callers. */
  cabinetTotalH?: number;
  /** Joint method override — when provided, replaces the per-box default
   *  from `resolveJointMethod(box)`. Production callers (`useCabinet`,
   *  `CabinetSketch`) compute this once at cabinet level via
   *  {@link resolveCabinetJointMethod} so every body in the cabinet shares
   *  the same top/bottom-panel cut formula. */
  joint?: JointMethod;
  /** Top-panel structural variant — forwarded from `CabinetInput.topVariant`.
   *  Defaults to `'standard'` when absent. */
  topVariant?: 'standard' | 'sink-open';
  /** Standing height (vertical, cm) of each sink traverse — the dimension
   *  visible in the front view. Boards are oriented vertically: length=innerW,
   *  width=this value, thickness=t. Only relevant when `topVariant === 'sink-open'`.
   *  Defaults to 10 cm. */
  sinkTraverseWidthCm?: number;
}

export function buildBoardModel(args: BuildBoardModelArgs): Board[] {
  const {
    box, bodyMaterial, frontMaterial,
    hasEnvelopeLeft, hasEnvelopeRight, hasEnvelopeTop,
    items, hasPartition, cellItems,
    hasBack = true,
    envelopeDepth,
    backThicknessCm = BACK_THICKNESS_CM,
    cabinetTotalH,
    joint: jointOverride,
    topVariant = 'standard',
    sinkTraverseWidthCm = 10,
  } = args;

  if (box.level === 'plinth') return [];

  const t = bodyMaterial.thickness / 10;   // cm
  const tF = frontMaterial.thickness / 10; // cm
  const W = box.W;
  const H = box.H;
  const D = box.D;
  // Envelope panels span the full cabinet depth — that includes the back
  // panel + hinge gap + front thickness that box.D already excluded.
  const envD = envelopeDepth ?? D;
  // Envelope side length: full external cabinet height minus the floor gap
  // for plastic levelers. Defaults to this body's H so legacy callers and
  // unit tests keep working when they only care about a single body.
  const envSideLength = (cabinetTotalH ?? H) - LEVELER_GAP_CM;
  const matId = bodyMaterial.id;
  const frontMatId = frontMaterial.id;
  const joint = jointOverride ?? resolveJointMethod(box);

  const out: Board[] = [];
  // Container sub-key used for every board emitted on behalf of this body —
  // each role is unique within a body, so role+boxKey is a stable id.
  const boxKey = boxStableKey(box);

  // ── Sides + top + bottom ──────────────────────────────────────────────────
  const sinkOpen = topVariant === 'sink-open';
  // Standing boards (vertical): tw is the visible HEIGHT in the front view
  // (10cm default). In 3D: length=innerW, width=tw (standing height),
  // thickness=t. Front board occupies front depth, back board occupies back
  // depth — but in the 2D front view they overlap at yFrom=0, yTo=tw.
  const tw = sinkTraverseWidthCm;

  if (joint === 'rabbet') {
    out.push({
      id: newItemId(), stableId: boardStableId('side-left', boxKey),
      role: 'side-left', materialId: matId,
      length: H, width: D, thickness: t,
      xFrom: 0, xTo: t, yFrom: 0, yTo: H, visible: true,
    });
    out.push({
      id: newItemId(), stableId: boardStableId('side-right', boxKey),
      role: 'side-right', materialId: matId,
      length: H, width: D, thickness: t,
      xFrom: W - t, xTo: W, yFrom: 0, yTo: H, visible: true,
    });
    if (sinkOpen) {
      out.push({
        id: newItemId(), stableId: boardStableId('sink-traverse-front', boxKey),
        role: 'sink-traverse-front', materialId: matId,
        length: W - 2 * t, width: tw, thickness: t,
        xFrom: t, xTo: W - t, yFrom: 0, yTo: tw, visible: true,
      });
      out.push({
        id: newItemId(), stableId: boardStableId('sink-traverse-back', boxKey),
        role: 'sink-traverse-back', materialId: matId,
        length: W - 2 * t, width: tw, thickness: t,
        xFrom: t, xTo: W - t, yFrom: 0, yTo: tw, visible: true,
      });
    } else {
      out.push({
        id: newItemId(), stableId: boardStableId('top', boxKey),
        role: 'top', materialId: matId,
        length: W - 2 * t, width: D, thickness: t,
        xFrom: t, xTo: W - t, yFrom: 0, yTo: t, visible: true,
      });
    }
    out.push({
      id: newItemId(), stableId: boardStableId('bottom', boxKey),
      role: 'bottom', materialId: matId,
      length: W - 2 * t, width: D, thickness: t,
      xFrom: t, xTo: W - t, yFrom: H - t, yTo: H, visible: true,
    });
  } else {
    if (sinkOpen) {
      out.push({
        id: newItemId(), stableId: boardStableId('sink-traverse-front', boxKey),
        role: 'sink-traverse-front', materialId: matId,
        length: W, width: tw, thickness: t,
        xFrom: 0, xTo: W, yFrom: 0, yTo: tw, visible: true,
      });
      out.push({
        id: newItemId(), stableId: boardStableId('sink-traverse-back', boxKey),
        role: 'sink-traverse-back', materialId: matId,
        length: W, width: tw, thickness: t,
        xFrom: 0, xTo: W, yFrom: 0, yTo: tw, visible: true,
      });
    } else {
      out.push({
        id: newItemId(), stableId: boardStableId('top', boxKey),
        role: 'top', materialId: matId,
        length: W, width: D, thickness: t,
        xFrom: 0, xTo: W, yFrom: 0, yTo: t, visible: true,
      });
    }
    out.push({
      id: newItemId(), stableId: boardStableId('bottom', boxKey),
      role: 'bottom', materialId: matId,
      length: W, width: D, thickness: t,
      xFrom: 0, xTo: W, yFrom: H - t, yTo: H, visible: true,
    });
    out.push({
      id: newItemId(), stableId: boardStableId('side-left', boxKey),
      role: 'side-left', materialId: matId,
      length: H - 2 * t, width: D, thickness: t,
      xFrom: 0, xTo: t, yFrom: t, yTo: H - t, visible: true,
    });
    out.push({
      id: newItemId(), stableId: boardStableId('side-right', boxKey),
      role: 'side-right', materialId: matId,
      length: H - 2 * t, width: D, thickness: t,
      xFrom: W - t, xTo: W, yFrom: t, yTo: H - t, visible: true,
    });
  }

  // ── Partition ────────────────────────────────────────────────────────────
  if (hasPartition) {
    out.push({
      id: newItemId(), stableId: boardStableId('partition', boxKey),
      role: 'partition', materialId: matId,
      length: H - 2 * t, width: D, thickness: t,
      xFrom: (W - t) / 2, xTo: (W + t) / 2, yFrom: t, yTo: H - t, visible: true,
    });
  }

  // ── Shelves ──────────────────────────────────────────────────────────────
  // Shelves apply BOTH the inner-clear (W - 2·tBody) AND a per-side reveal
  // so they slide without binding against the carcass sides. Depth is also
  // reduced so the shelf sits behind the door line.
  function shelfYRange(hf: number): { yFrom: number; yTo: number } {
    return { yFrom: H - hf - t, yTo: H - hf };
  }

  function pushShelf(item: ShelfItem, xFrom: number, xTo: number): void {
    const y = shelfYRange(item.heightFromFloor);
    const role: BoardRole = item.isFixedAboveExternals === true ? 'fixed-shelf' : 'shelf';
    const visibleSpan = xTo - xFrom;
    out.push({
      id: newItemId(),
      // Shelves persist across calculate() runs via the interior state; the
      // shelf item's own id is stable, so role+box+shelfId is too.
      stableId: boardStableId(role, `${boxKey}@${item.id}`),
      role, materialId: matId,
      length: visibleSpan - 2 * SHELF_WIDTH_REVEAL_CM,
      width: D - SHELF_DEPTH_REVEAL_CM,
      thickness: t,
      xFrom, xTo, yFrom: y.yFrom, yTo: y.yTo, visible: true,
    });
  }

  if (hasPartition && cellItems) {
    const rightX = { from: (W + t) / 2, to: W - t };
    const leftX  = { from: t, to: (W - t) / 2 };
    for (const it of cellItems[0]) if (it.type === 'shelf') pushShelf(it, rightX.from, rightX.to);
    for (const it of cellItems[1]) if (it.type === 'shelf') pushShelf(it, leftX.from, leftX.to);
  } else {
    for (const it of items) if (it.type === 'shelf') pushShelf(it, t, W - t);
  }

  // ── Internal shelves (merged-body structural splits) ─────────────────────
  // Heights are absolute (cm from cabinet floor) and stable for a given
  // merged-body decomposition — use them as the per-shelf sub-key.
  if (box.internalShelves) {
    for (const hf of box.internalShelves) {
      const y = shelfYRange(hf);
      out.push({
        id: newItemId(),
        stableId: boardStableId('internal-shelf', `${boxKey}@h${hf}`),
        role: 'internal-shelf', materialId: matId,
        length: (W - 2 * t) - 2 * SHELF_WIDTH_REVEAL_CM,
        width: D - SHELF_DEPTH_REVEAL_CM,
        thickness: t,
        xFrom: t, xTo: W - t, yFrom: y.yFrom, yTo: y.yTo, visible: true,
      });
    }
  }

  // ── Back panel (invisible in front view, still cut) ──────────────────────
  // The back is cut to the OUTER dimensions of the body (W × H) so it
  // overlays the back face of the carcass — covering the rear edges of the
  // side / top / bottom panels rather than slotting between them.
  if (hasBack) {
    out.push({
      id: newItemId(), stableId: boardStableId('back', boxKey),
      role: 'back', materialId: matId,
      length: W, width: H, thickness: backThicknessCm,
      xFrom: 0, xTo: W, yFrom: 0, yTo: H, visible: false,
    });
  }

  // ── Envelope ─────────────────────────────────────────────────────────────
  // Envelope panels use `envD` (full cabinet depth) rather than box.D
  // (carcass depth) — the outer shell wraps around the back panel and the
  // hinge gap that the carcass excludes. envelope-left/right length spans
  // the FULL external cabinet height (cabinetTotalH, including plinth)
  // minus LEVELER_GAP_CM for the plastic levelers under the cabinet.
  if (hasEnvelopeLeft) {
    out.push({
      id: newItemId(), stableId: boardStableId('envelope-left', boxKey),
      role: 'envelope-left', materialId: frontMatId,
      length: envSideLength, width: envD, thickness: tF,
      xFrom: -tF, xTo: 0, yFrom: 0, yTo: H, visible: true,
    });
  }
  if (hasEnvelopeRight) {
    out.push({
      id: newItemId(), stableId: boardStableId('envelope-right', boxKey),
      role: 'envelope-right', materialId: frontMatId,
      length: envSideLength, width: envD, thickness: tF,
      xFrom: W, xTo: W + tF, yFrom: 0, yTo: H, visible: true,
    });
  }
  if (hasEnvelopeTop) {
    out.push({
      id: newItemId(), stableId: boardStableId('envelope-top', boxKey),
      role: 'envelope-top', materialId: frontMatId,
      length: W, width: envD, thickness: tF,
      xFrom: 0, xTo: W, yFrom: -tF, yTo: 0, visible: true,
    });
  }

  return out;
}

// ── Plinth board model ──────────────────────────────────────────────────────
// The plinth is a kick-board cabinet base. Unlike carcass boards (which are
// per-body), the plinth is constructed once for the whole cabinet:
//
//   ┌─────────────────────────────────────────┐  ← plinth-back  (visual y top)
//   │  ▓                ▓                ▓    │
//   │  ▓ L              ▓                ▓ L  │     gables (L-shapes) in between
//   │  ▓                ▓                ▓    │
//   └─────────────────────────────────────────┘  ← plinth-front (visual y bot)
//
// Visual coordinates here are TOP-VIEW: x = cabinet-width axis (0..cabinetW),
// y = cabinet-depth axis (0 = front, cabinetD = back).
//
// A "gable" is an L-shape vertical support: panel A is a thin standing wall
// (tBody × (D-2t) × (plinthH-0.6)), panel B is a flat cap lying on top
// ((plinthH-0.6) × (D-2t) × tBody). Both cut to the same flat size
// `(D-2t) × (plinthH-0.6)`. Gables sit:
//   - flush at the left edge (x=0).
//   - flush at the right edge (x=cabinetW), mirrored.
//   - centered at every joint between adjacent bottom-row bodies.
//   - mid-body for any body whose width > 80 cm (extra support).

export interface PlinthGable {
  /** Stable identifier across cabinet rebuilds — used as the override-map
   *  key in {@link BuildPlinthBoardModelArgs.gableOverrides}. Edge gables
   *  are singletons; joint and mid-body gables index by emission order
   *  within their kind: `joint:0`, `joint:1`, `mid-body:0`, etc. The ID
   *  survives plinth-height changes and identical box decompositions; a
   *  decomposition change that adds/removes gables shifts indices and
   *  stale overrides drop silently. */
  id: string;
  /** Cabinet-X position the gable is anchored on. Edge gables flush their
   *  Panel A against this side; internal gables center Panel A's thickness
   *  on this x. */
  xAnchor: number;
  /** Which side Panel B (the flat cap) extends to.
   *  - 'right': Panel B is at higher x than Panel A (the default).
   *  - 'left':  Panel B is at lower x than Panel A (right-edge mirror).
   *  - 'flush-left': Panel A at x=[0, tBody], Panel B to its right.
   *  - 'flush-right': Panel A at x=[cabinetW-tBody, cabinetW], Panel B to its left.
   *  The direction stays fixed across drags — it only determines WHICH SIDE
   *  Panel B extends. Panel A's actual x is `userPositionX ?? default(direction, xAnchor)`. */
  direction: 'right' | 'left' | 'flush-left' | 'flush-right';
  /** Diagnostic — origin of this gable, useful for tests and the editor. */
  kind: 'edge-left' | 'edge-right' | 'joint' | 'mid-body';
  /** User override for Panel A's left-edge cabinet-X. When set, replaces
   *  the default position computed from {@link kind} + {@link xAnchor} +
   *  {@link direction}. Always in cm. Set by the editor's drag; cleared
   *  by `resetPlinthGableOverrides()` (which clears every override at once).
   *  Plumbed from the caller's `gableOverrides` map onto the returned
   *  gable for convenience — `calcPlinthGables` itself ignores the map's
   *  semantics; the caller injects the value. */
  userPositionX?: number;
}

/** Width snap step (cm) for the editor's gable drag. Coarser than
 *  `INPUT_PRECISION_MM` because positioning a plinth gable to a tenth of
 *  a millimetre is meaningless — 0.5 cm matches what a carpenter eyeballs
 *  on the floor. */
export const PLINTH_GABLE_SNAP_CM = 0.5;

/** Default Panel-A left-edge x for a gable, given its kind/direction/xAnchor.
 *  Used as the fallback whenever `gableOverrides` doesn't carry an entry for
 *  the gable. Pure function — does not consult any state. */
export function defaultPlinthGableLeftX(gable: PlinthGable, tBody: number, cabinetW: number): number {
  switch (gable.direction) {
    case 'flush-left':  return 0;
    case 'flush-right': return cabinetW - tBody;
    case 'right':
    case 'left':
      return gable.xAnchor - tBody / 2;
  }
}

/** Effective Panel-A left-edge x: override if present, else default. */
export function effectivePlinthGableLeftX(
  gable: PlinthGable,
  tBody: number,
  cabinetW: number,
): number {
  return gable.userPositionX ?? defaultPlinthGableLeftX(gable, tBody, cabinetW);
}

/** Snap a proposed drag x (cm) to the editor's grid. */
export function snapPlinthGableX(x: number): number {
  return Math.round(x / PLINTH_GABLE_SNAP_CM) * PLINTH_GABLE_SNAP_CM;
}

/** Clamp a proposed Panel-A left-edge x so the gable stays inside the
 *  plinth and does not overlap any other gable. Other gables are treated
 *  as their CURRENT effective positions (overrides included). Adjacent
 *  gables enforce a minimum centre-to-centre distance of `tBody` —
 *  Panel A intervals `[x, x+tBody]` may not overlap. Returns the closest
 *  legal position to the proposed; if no legal slot exists at all (cabinet
 *  too narrow for the remaining gables), returns the proposed x clamped to
 *  the cabinet edges (caller decides whether to commit). */
export function clampPlinthGableX(args: {
  proposedX: number;
  gableId: string;
  allGables: readonly PlinthGable[];
  cabinetW: number;
  tBody: number;
}): number {
  const { proposedX, gableId, allGables, cabinetW, tBody } = args;
  // Step 1: clamp to cabinet bounds.
  const target = Math.max(0, Math.min(proposedX, cabinetW - tBody));
  // Step 2: carve the cabinet into legal gap intervals by subtracting each
  // other gable's forbidden zone `[ox - tBody, ox + tBody]` from the full
  // [0, cabinetW - tBody] range. Then choose the gap point closest to target.
  const others = allGables
    .filter(g => g.id !== gableId)
    .map(g => effectivePlinthGableLeftX(g, tBody, cabinetW))
    .sort((a, b) => a - b);
  let gaps: Array<[number, number]> = [[0, cabinetW - tBody]];
  for (const ox of others) {
    const forbidLo = ox - tBody;
    const forbidHi = ox + tBody;
    const next: Array<[number, number]> = [];
    for (const [lo, hi] of gaps) {
      if (hi <= forbidLo || lo >= forbidHi) {
        next.push([lo, hi]);
      } else {
        if (lo < forbidLo) next.push([lo, forbidLo]);
        if (forbidHi < hi) next.push([forbidHi, hi]);
      }
    }
    gaps = next;
  }
  if (gaps.length === 0) return target;
  let best = target;
  let bestDist = Infinity;
  for (const [lo, hi] of gaps) {
    const x = Math.max(lo, Math.min(target, hi));
    const dist = Math.abs(x - target);
    if (dist < bestDist) { bestDist = dist; best = x; }
  }
  return best;
}

/** Threshold above which a single body gets an extra middle gable. */
export const PLINTH_GABLE_MID_BODY_THRESHOLD_CM = 80;

/** Computes the gable positions for the cabinet's plinth. `boxes` must be
 *  the BOTTOM-ROW bodies (not plinth boxes themselves, not top/middle rows).
 *  The caller is expected to filter; this function does not validate
 *  `box.level`. */
export function calcPlinthGables(cabinetW: number, boxes: Box[], tBody: number): PlinthGable[] {
  const gables: PlinthGable[] = [];

  // Left edge — Panel A flush at x=0. Stable id 'edge-left' — singleton.
  gables.push({ id: 'edge-left', xAnchor: 0, direction: 'flush-left', kind: 'edge-left' });

  // Internal joints + mid-body extras. Sort boxes by their left x in the row.
  const sorted = [...boxes].sort((a, b) => positionRank(a) - positionRank(b));
  let cumX = 0;
  let midBodyIdx = 0;
  let jointIdx = 0;
  for (let i = 0; i < sorted.length; i++) {
    const box = sorted[i]!;
    // Mid-body gable for wide bodies.
    if (box.W > PLINTH_GABLE_MID_BODY_THRESHOLD_CM) {
      gables.push({
        id: `mid-body:${midBodyIdx}`,
        xAnchor: cumX + box.W / 2,
        direction: 'right',
        kind: 'mid-body',
      });
      midBodyIdx++;
    }
    cumX += box.W;
    // Joint between this body and the next.
    if (i < sorted.length - 1) {
      gables.push({
        id: `joint:${jointIdx}`,
        xAnchor: cumX,
        direction: 'right',
        kind: 'joint',
      });
      jointIdx++;
    }
  }

  // Right edge — Panel A flush at x=cabinetW. Stable id 'edge-right'.
  gables.push({ id: 'edge-right', xAnchor: cabinetW, direction: 'flush-right', kind: 'edge-right' });

  // Don't suppress tBody — keep gables for unused boxes etc; the caller can
  // skip the call when plinth is absent.
  void tBody;
  return gables;
}

/** Sort key reused from the existing sketch ordering: 'single'/'left' first,
 *  then 'right', then unit_N by index. Plinth-row bodies typically follow
 *  the bottom-row decomposition so this matches the visual order. */
function positionRank(box: Box): number {
  if (box.position === 'single' || box.position === 'left') return 0;
  if (box.position === 'right') return 1;
  return box.unitIndex ?? 0;
}

export interface BuildPlinthBoardModelArgs {
  cabinetW: number;
  cabinetD: number;
  plinthHeight: number;
  bodyMaterial: Material | (Omit<Material, 'id'> & { id: string });
  /** Bottom-row body boxes (caller filters out plinth boxes and other rows).
   *  Used to compute internal gable positions. */
  boxes: Box[];
  /** Per-gable Panel-A left-edge x overrides keyed by `PlinthGable.id`.
   *  A number replaces the default position; an absent key falls back to
   *  the flush/centered default. The editor's free-form drag writes here. */
  gableOverrides?: ReadonlyMap<string, number>;
  /** Front-material override for the plinth's cladding panel. When provided,
   *  an additional `plinth-front-cladding` board is emitted at the cabinet
   *  front (same length × height as plinth-front, thickness = frontMaterial
   *  thickness), and the body-material `plinth-front` shifts back by that
   *  thickness — the carcass keeps the cabinet's external footprint while
   *  the visible facade gets a separate, replaceable cladding piece. Pass
   *  `undefined` to skip cladding entirely (legacy / unit tests). */
  frontMaterial?: Material | (Omit<Material, 'id'> & { id: string });
  /** Recess depth in cm — pushes the plinth back from the cabinet's front
   *  face. The cabinet footprint stays at `cabinetD`; the plinth structure
   *  (cladding + plinth-front + gables + plinth-back) sits inside it,
   *  starting at `y = recessCm`. Defaults to 0 (no recess). */
  recessCm?: number;
}

/** Emits every board in the plinth (front, back, and each gable's Panel A +
 *  Panel B). Returns [] when plinthHeight <= 0. Boards' xFrom/yFrom etc are
 *  in TOP-VIEW coordinates (y = depth) per the dual semantic documented on
 *  `Board.yFrom`. */
export function buildPlinthBoardModel(args: BuildPlinthBoardModelArgs): Board[] {
  const {
    cabinetW, cabinetD, plinthHeight, bodyMaterial, boxes,
    gableOverrides, frontMaterial, recessCm = 0,
  } = args;
  if (plinthHeight <= 0) return [];

  const t = bodyMaterial.thickness / 10; // cm
  const matId = bodyMaterial.id;
  // The plinth panels are cut LEVELER_GAP_CM short so the cabinet sits on
  // plastic levelers — same rationale as the envelope sides.
  const panelH = Math.max(0, plinthHeight - LEVELER_GAP_CM);
  // Cladding piece (front material) — sits as a separate front face. When
  // present, the body-material plinth-front retreats by tFront so the
  // cabinet's external footprint at the front stays exactly `recess + 0`.
  const tFront = frontMaterial ? frontMaterial.thickness / 10 : 0;
  const hasCladding = !!frontMaterial;
  // Recess pushes the entire plinth structure (cladding + front + gables +
  // back) back from the cabinet's front face. Negative values are clamped.
  const recess = Math.max(0, recessCm);
  // Y positions along the cabinet's depth axis (top-view):
  //   recess              cladding starts
  //   recess + tFront     plinth-front starts (body material)
  //   recess + tFront+ t  gables start
  //   cabinetD - t        plinth-back starts
  //   cabinetD            plinth-back ends (cabinet rear face).
  const claddingYFrom = recess;
  const claddingYTo   = recess + tFront;
  const frontYFrom    = claddingYTo;
  const frontYTo      = frontYFrom + t;
  const backYFrom     = cabinetD - t;
  const backYTo       = cabinetD;
  // Gable cut length (the inner edge runs across the plinth's depth between
  // the body-material front and back panels — cladding is OUTSIDE this).
  const gableLength = Math.max(0, backYFrom - frontYTo);
  const out: Board[] = [];

  // Cladding — facade panel, full cabinet width, front material.
  if (hasCladding) {
    out.push({
      id: newItemId(), stableId: boardStableId('plinth-front-cladding'),
      role: 'plinth-front-cladding', materialId: frontMaterial!.id,
      length: cabinetW, width: panelH, thickness: tFront,
      xFrom: 0, xTo: cabinetW, yFrom: claddingYFrom, yTo: claddingYTo, visible: true,
    });
  }

  // Front and back strips — body material. The front sits behind the
  // cladding when present, behind the recess gap when recessed. Singletons
  // at the cabinet level → stable id is just the role.
  out.push({
    id: newItemId(), stableId: boardStableId('plinth-front'),
    role: 'plinth-front', materialId: matId,
    length: cabinetW, width: panelH, thickness: t,
    xFrom: 0, xTo: cabinetW, yFrom: frontYFrom, yTo: frontYTo, visible: true,
  });
  out.push({
    id: newItemId(), stableId: boardStableId('plinth-back'),
    role: 'plinth-back', materialId: matId,
    length: cabinetW, width: panelH, thickness: t,
    xFrom: 0, xTo: cabinetW, yFrom: backYFrom, yTo: backYTo, visible: true,
  });

  // Gables — Panel A is the vertical wall (top-view: tBody wide × gableLength
  // deep). Panel B is the flat cap on top of A (top-view: panelH wide ×
  // gableLength deep). Both panels' Y range is [frontYTo, backYFrom]. An
  // override in `gableOverrides` (keyed by gable.id) replaces Panel A's
  // default left-edge x; the direction still controls where Panel B extends.
  const gables = calcPlinthGables(cabinetW, boxes, t).map<PlinthGable>(g => {
    const override = gableOverrides?.get(g.id);
    return override !== undefined ? { ...g, userPositionX: override } : g;
  });
  const panelBWidth = panelH; // the lying-flat Panel B is `panelH` wide in plan view
  for (const g of gables) {
    // Panel A's left edge — override wins, else direction's default.
    const aFrom = g.userPositionX ?? defaultPlinthGableLeftX(g, t, cabinetW);
    const aTo   = aFrom + t;
    const panelBOnLeft = g.direction === 'left' || g.direction === 'flush-right';
    const bFrom = panelBOnLeft ? aFrom - panelBWidth : aTo;
    const bTo   = panelBOnLeft ? aFrom              : aTo + panelBWidth;
    // Gable Panels A/B use the gable's already-stable id as the sub-key,
    // so dragging never invalidates a stored override.
    out.push({
      id: newItemId(), stableId: boardStableId('plinth-gable-a', g.id),
      role: 'plinth-gable-a', materialId: matId,
      length: gableLength, width: panelH, thickness: t,
      xFrom: aFrom, xTo: aTo, yFrom: frontYTo, yTo: backYFrom, visible: true,
    });
    out.push({
      id: newItemId(), stableId: boardStableId('plinth-gable-b', g.id),
      role: 'plinth-gable-b', materialId: matId,
      length: gableLength, width: panelH, thickness: t,
      xFrom: bFrom, xTo: bTo, yFrom: frontYTo, yTo: backYFrom, visible: true,
    });
  }

  return out;
}

// ── Board → CutItem conversion ───────────────────────────────────────────────
// Translates the physical board model into the cut-list format used by the
// saw operator and the sheet calculator. Includes ALL boards (visible flag
// drives sketch rendering only; the back panel is invisible but still
// physically cut).

const ROLE_NAME_HE: Record<BoardRole, string> = {
  'side-left': 'צד שמאל',
  'side-right': 'צד ימין',
  'top': 'עליון',
  'bottom': 'תחתון',
  'shelf': 'מדף',
  'partition': 'מחיצה',
  'fixed-shelf': 'מדף קבוע',
  'internal-shelf': 'מדף מבני',
  'envelope-left': 'מעטפת — צד שמאל',
  'envelope-right': 'מעטפת — צד ימין',
  'envelope-top': 'מעטפת תקרה',
  'back': 'גב',
  'plinth-front': 'צוקל קדמי',
  'plinth-back': 'צוקל אחורי',
  'plinth-gable-a': 'גיבל צוקל א׳',
  'plinth-gable-b': 'גיבל צוקל ב׳',
  'plinth-front-cladding': 'חיפוי צוקל',
  'sink-traverse-front': 'קורת רוחב קדמית',
  'sink-traverse-back': 'קורת רוחב אחורית',
};

const ROLE_GROUP: Record<BoardRole, CutGroup> = {
  'side-left': 'body',
  'side-right': 'body',
  'top': 'body',
  'bottom': 'body',
  'shelf': 'body',
  'partition': 'body',
  'fixed-shelf': 'body',
  'internal-shelf': 'body',
  'envelope-left': 'shell',
  'envelope-right': 'shell',
  'envelope-top': 'shell',
  'back': 'back',
  'plinth-front': 'plinth',
  'plinth-back': 'plinth',
  'plinth-gable-a': 'plinth',
  'plinth-gable-b': 'plinth',
  'plinth-front-cladding': 'plinth',
  'sink-traverse-front': 'body',
  'sink-traverse-back': 'body',
};

/** Translates boards → CutItems. Reads EFFECTIVE values via
 *  {@link getDimension} / {@link getMaterial} so any per-board override
 *  (length/width/thickness/material) wins over the derived carpentry-rule
 *  value. When `edgingCtx` is provided, also deducts the edge-banding from
 *  the relevant dimension(s) per role — see {@link getEdgingPattern} and
 *  {@link getDeductionFor}. Omitting `edgingCtx` skips the deduction
 *  entirely (legacy callers / unit tests that don't simulate banding).
 *  `boxSlotId` identifies the slot these boards belong to and is forwarded
 *  to {@link resolveEdging}; omit for cabinet-level singletons (the plinth
 *  family — they all resolve to pattern `'none'` anyway). */
export function boardsToCutItems(
  boards: Board[],
  label: string,
  overrides: ReadonlyMap<string, BoardOverrides> = new Map(),
  edgingCtx?: EdgingContext,
  boxSlotId?: BoxSlotId,
): CutItem[] {
  const tag = label ? ` — ${label}` : '';
  return boards.map(b => {
    const length    = getDimension(b, 'length',    overrides);
    const width     = getDimension(b, 'width',     overrides);
    const thickness = getDimension(b, 'thickness', overrides);
    const materialId = getMaterial(b, overrides);
    // Edge-banding deduction: zero unless an edging context was passed in.
    const pattern   = getEdgingPattern(b.role);
    const edging    = edgingCtx ? resolveEdging(b, boxSlotId, edgingCtx) : undefined;
    const dLen      = edging ? getDeductionFor(pattern, 'length', edging) : 0;
    const dWid      = edging ? getDeductionFor(pattern, 'width',  edging) : 0;
    const noteMm = `${Math.round(thickness * 10)}mm`;
    // Back panels and plinth boards are anonymous to the saw operator —
    // they are not per-body pieces and only their dimensions matter.
    // Dropping the body tag lets identical backs (and the cabinet-level
    // plinth boards) collapse into single rows in mergeCutItems.
    const isAnonymous = b.role === 'back' || b.role.startsWith('plinth-');
    const nameTag = isAnonymous ? '' : tag;
    return {
      name: `${ROLE_NAME_HE[b.role]}${nameTag}`,
      qty: 1,
      // 0.01 mm precision: Math.round(...*1000)/100 avoids the integer-mm
      // rounding that would hide a 0.7 mm edging-deduction difference (the
      // gap between 0.6 mm and 1.3 mm bands). CutsList's format2 handles
      // display rounding; mergeCutItems uses template-string keys so float
      // equality is exact for boards sharing the same edging. :contentReference[oaicite:0]{index=0}
      w: Math.round((length - dLen) * 1000) / 100,
      h: Math.round((width  - dWid) * 1000) / 100,
      group: ROLE_GROUP[b.role],
      note: noteMm,
      materialId,
      // Carried through so mergeCutItems can detect role pairs (e.g. top +
      // bottom of same dims → "עליון / תחתון").
      role: b.role,
    } satisfies CutItem;
  });
}
